### ISSUE TITLE
Add README and LICENSE and explain build & deployment process

### ISSUE THREAD

**Issue by hjacobs** [zalando/zalando.github.io#1]
I commited a change in this repo as I was unaware of the build & deploy process, please explain it clearly in a (new) README and add a LICENSE file too.

**Comment by rbarilani** [comment]
@hjacobs Yep we should add a specific README for the distribution repository and also a LICENSE file and a MAINTAINERS file. The open source guide lines were not defined when we started this project during ours on-boarding period.

@janloeffler Who who could be the maintainer? Which role has a maintainer? Which power and whic responsabilities? We should clarify that or if we already did this clarification, can you put a reference where we can find those infos? Thanks in advance.

**Comment by rbarilani** [comment]
moved to https://github.com/zalando/zalando.github.io-dev/issues/21
