### ISSUE TITLE
Collect missing data for monitoring

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#115]
## Collect missing data for Roadblock

Figure out if we need anything more to collect and visualise the monitoring data.

### Tasks

- [x] Activity logs
- [x] Compare with KPIs
- [x] Tech Radar stats

### Expected delivery

We have all the data in place for the monitoring infrastructure.

**Comment by perploug** [comment]
Tech radar projects to watch:

https://github.com/akka/akka
https://github.com/nodejs/node
https://github.com/OAI/OpenAPI-Specification
https://github.com/playframework/playframework
https://github.com/facebook/react
https://github.com/ReactiveX/RxJava
https://github.com/scikit-learn/scikit-learn
https://github.com/spring-projects/spring-framework

https://github.com/moby/moby
https://github.com/haproxy/haproxy
https://github.com/Netflix/Hystrix
https://github.com/eclipse/jetty.project
https://github.com/kubernetes/kubernetes/

https://github.com/elastic/elasticsearch
https://github.com/coreos/etcd
https://github.com/postgres/postgres
https://github.com/antirez/redis

**Comment by perploug** [comment]
I think we need this for the external collaborators: 
https://developer.github.com/v3/orgs/outside_collaborators/

Should be stored in Collaborators table with an identity id, login, user_id and organisation_id
(copy from hipchat for reference)

**Comment by perploug** [comment]
For external collaborators on zalando projects, this is the endpoint:
https://developer.github.com/v3/repos/collaborators/#list-collaborators

Should go into a table with a many to many relationship to repositories, so a collaborator will be there multiple times and we can do a compare with our members

**Comment by perploug** [comment]
Status on KPIs versus the data we collect:

- ✅ (wip( #external contributors to Zalando’s open source projects
- ✅ #projects on GitHub.com
- ✅ Project activity
- ✅ #Stars on Zalando’s open source projects
- ✅ (WIP) #Merged PRs from Zalando to projects on the Tech Radar’s “Adopt” level.
- ✅ (we will collect repo collaborators and see who have write/admin rights) #of Zalando Open Source project maintainers.
- ⚠️ (requires data from people.zalando)#External contributors on GitHub converted to Zalando organization members.
- ❌ (out of scope) #Non-team merged PRs to GHE repositories.
- ❌ (out of scope) #GHE repos compliant with OSS rules of play
