### ISSUE TITLE
Submit Talk To OSSEU

### ISSUE THREAD

**Issue by baggerspion** [zalando/zalando.github.io#120]
## Task Headline

We should submit a talk to [Open Source Summit Europe](https://events.linuxfoundation.org/events/open-source-summit-europe-2018/). It is a high profile event and a good opportunity for us to talk about our work here.

### Tasks

- [x] Brainstorm Topic(s)
- [x] Write & Submit Proposal(s)

### Expected delivery

At least one talk submission is made to OSSEU.

## Stakeholders

- [x] EB
- [x] CC
- [ ] OSG

## How do we measure the task was completed

- Number of submitted talks
- Number of accepted talks

**Comment by perploug** [comment]
Github universe also has a call for speakers: https://githubuniverse.com/

**Comment by perploug** [comment]
Talk submitted
