### ISSUE TITLE
Project filter not working

### ISSUE THREAD

**Issue by rejas** [zalando/zalando.github.io#124]
Wanted to take a look at your projects at https://opensource.zalando.com/projects/index.html

Alas the console throws the following errors and the loading spinner never ends with no results being displayed:

```
index.js:2 GET https://catwatch.opensource.zalan.do/statistics?organizations=zalando 0 ()
  getData @ index.js:2
  displayStatistics @ index.js:142
  init @ index.html:120
  (anonymous) @ index.html:123

index.html:121 Uncaught (in promise) TypeError: Failed to fetch
  async function (async)
  init @ index.html:116
  (anonymous) @ index.html:123
```

Doesnt work under latest Chrome and Firefox.

**Comment by baggerspion** [comment]
@rejas Thanks for your report! At the moment we are unable to reproduce this. We will leave the issue open a little longer to see if anyone else comes forward with the same issue. Most likely, the JS was unable to talk to the CatWatch backend for some reason.

**Comment by rejas** [comment]
Yeah, colleagues get it to work from our network too so I guess some weird firewall/hosts rule specific to my pc is the culprit. Closing it for now. Thx for the quick reponse.
