### ISSUE TITLE
Bootcamp materials on Open Source

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#129]
## Task Headline

In order to create awareness of Zalandos open source efforts and the possibilities that techies have to
contribute to these efforts, we will develop a onboarding presentation to be presented as part of the 
tech onboarding each month.

There is already a presentation on the GH structure, made for the customer fair, which can be used as a baseline, notice comments on this in #157 

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [x] Decide on scope and content of the presentation
- [x] Get clarity of the legal aspects of OSS contribution
- [x] Design presentation

### Expected delivery

What is the concrete outcome of this work: 

Presentation files for the tech onboarding and a dedicated 30 minutes in the tech onboarding days every month. 

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Tech academy
- [x] Compliance / legal

## How do we measure the task was completed
How do we measure impact 

  1. Number of onboardees getting exposed to the os presentation

**Comment by perploug** [comment]
Structure of the course available for review here:
https://docs.google.com/document/d/14zgMVM9TxC5WRYw67iUiAAwOlBl1KuvF15QkvAaBsp8/edit#

**Comment by perploug** [comment]
Wrapped up the slides for the presentation, ready for review and a test run>
https://docs.google.com/presentation/d/1epaCAsyWzyBaTKJheTgmoLELVAcOwCToC2Jk51jNrMg/edit#slide=id.g10dae75427_0_294

**Comment by perploug** [comment]
Awaiting review - updated based on your comment @hpdang

**Comment by hpdang** [comment]
I really like content from slide 21 to the end. The first half, I am a bit unsure, comments on the slide
