### ISSUE TITLE
Sort out the review group form

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#173]
## Task Headline

The review group form for submitting open source projects for approval is not ideal

- The form is publicly available
- The form collects unnessary information
- The form does not send a copy to the sender
- The form ends up somewhere there no-one monitors
- The review group does not take action

**Comment by perploug** [comment]
Putting together a new form based on the new docs, rather then attempting to change the current one, which I cannot find.

**Comment by perploug** [comment]
Places to update form links:
https://rulesofplay.docs.zalando.net/OS/os/
https://confluence.zalando.net/pages/editpage.action?pageId=100140977
https://github.bus.zalan.do/opensource/reviewgroupdocs

**Comment by perploug** [comment]
Updated form available for review here:
https://docs.google.com/a/zalando.de/forms/d/1yb_poR2LihYeC2AmRoj04c35-Pqtdc8EyyjXcQFe6EY/edit?usp=drive_web

Structure reflects the rules of play and the items we focus on when reviewing a project

**Comment by baggerspion** [comment]
- "Link to project" > Make it clear *what* link is expected (i.e. url for project in GHE)
- Sign-off... C8 *or above*
- License... not just AGPL to avoid. I would suggest simply linking to Annex 7 of the RoP and asking them to declare that they are in compliance with *that*
