### ISSUE TITLE
Finish open source strategy document

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#19]
Finish the challenge and guiding principles of the strategy document. Add roadmap for Q3 and Q4. 

- [x] Review and comment on the new structured document
- [x] Setup meeting with HH (friday)

**Comment by baggerspion** [comment]
Based upon previous feedback, I have restructured this text to follow Zalando's tech narrative standard.
Further work:
- [ ] complete "Background Information"
- [ ] further decisions to be made?
- [ ] peer review session
- [ ] present to stakeholders

**Comment by perploug** [comment]
Closed as the document is done, the meeting is set and if it does not pass review a new task will be opened.
