### ISSUE TITLE
Support CORS for https://opensource.zalando.com/problem/schema.yaml

### ISSUE THREAD

**Issue by rbarilani** [zalando/zalando.github.io#212]
## Task Headline

Hi Open source team, I would like to request CORS support for https://opensource.zalando.com/problem/schema.yaml...

Why?

In our team we use to expose ours swagger/open-api specifications using the well-known open source project called [swagger-ui](https://github.com/swagger-api/swagger-ui).
To respect zalando rest api guidelines we use https://opensource.zalando.com/problem/schema.yaml as a body for failing responses and to keep the swagger specification "DRY" we use to reference https://opensource.zalando.com/problem/schema.yaml as `$ref` but If that resource doesn't support CORS swagger-ui fails to load the references.

For more infos please see: https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/cors.md

WDYT?

Thanks in advance.

### Tasks
These are the concrete tasks to complete before the issue is marked as done:

- [ ] task 1
- [ ] task 2

### Expected delivery

What is the concrete outcome of this work: 

## Stakeholders
Who do we need to align with to make this happen? - add the deparment to get in touch with

- [ ] Department name

## How do we measure the task was completed
How do we measure impact 

  1. 
  1.
  1.

**Comment by perploug** [comment]
The schema file is hosted on https://github.com/zalando/problem and we don't have any direct control over that from here - it just uses the same domain. 

Github pages should support CORS by default, it is not something we can configure or control unfortunately.
