### ISSUE TITLE
Publish blog post introducing hong

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#229]
Tasks
- [x] Find a photo / get a team photo taken
- [x] [Read through the content](https://docs.google.com/document/d/1TYb9HN5tPDNLaNp7w15UFhMVtBmmgugOKMy1lL0F07A/edit)
- [ ] Convert to markdown
- [ ] Create a pull requests for a new blog post

**Comment by baggerspion** [comment]
Content looks good. Don't forget this needs a header image.

**Comment by baggerspion** [comment]
OK, I've done a further a review. We are missing a simple call to action, otherwise this is fine now. Converting this to Markdown and creating a PR should be super-easy for this article.
