### ISSUE TITLE
Project promotion - external sites to promote projects on

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#247]
As part of the project promotion framework, make a list of sites where projects can be promoted 

- [x] List of sites to promote on
- [x] Purpose / background of each site and how to post there
- [x] Template for how to announce

### Expected outcome
A list of ca. 10 sites where projects can be posted. Guidelines on how to use them and with a template for posting.

**Comment by hpdang** [comment]
please review https://docs.google.com/document/d/13CVbZEHuf3120089Ax_V6cvW_Ews-Dp1aKNfHxuuqxA/edit#heading=h.hw8f47pukd59

**Comment by baggerspion** [comment]
Looks good. Let's include @hjacobs suggestion about YouTube and then consider this "done" for now.
