### ISSUE TITLE
Presentation of the project promotion framework

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#251]
- [x] Prepare a slidedeck
- [x] Share with the team for feedback

**Comment by hpdang** [comment]
https://docs.google.com/presentation/d/1N76EmEQH9DkXX9Ml-jadcRBZ2h_jkq4qDWMSgOVl9DQ/edit#slide=id.g3b8aa6a332_0_1

**Comment by baggerspion** [comment]
This is great. Let's work out how to now tie the slides and documents together into some kind of "training package" for our maintainers.
