### ISSUE TITLE
Bootcamp: Create challenges/scenarios for exercise 3 (license/legal)

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#254]
- [x] Release project on personal github (Per)
- [x] Use of unlicensed code in Zalando's applications (Hong)  
- [x] Publish internal project on Zalando Github [use a GHE repo as example] (Per)
- [x] Use of open source dependencies with noncomplying license (Hong)
- [x] Zalando's Open Source Project maintainer leaves the company but still want to continue to work on this open source project (Per)

**Comment by hpdang** [comment]
Work in progress https://docs.google.com/document/d/1dIdEgbfPHlSRnYQj6mvq1o0qZ-FKO-Wa4xE-yNteayY/edit

**Comment by hpdang** [comment]
@perploug we are missing 3 scenarios

**Comment by perploug** [comment]
I rewrote the first 2 scenarios with other material which I think was a better fit content-wise, the full list of scenarios are available here for review: https://docs.google.com/document/d/1fcNImrK7rgxlxId8iHug_QAcpXMKhc40TvQZQzF9pI0/edit#
