### ISSUE TITLE
Figure out where and how to publish the promotion framework

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#262]
As the first 2 steps of the promotion framework is ready for pilot teams, we need to figure out how to make it available. 

- [x] Decide on where to host this (drive or opensource.z.com)
- [ ] Decide what be pushed to Zsolve
- [ ] Go over the format of the guide to make it easy to navigate

**Comment by hpdang** [comment]
Please review https://github.com/zalando/zalando.github.io/pull/280
