### ISSUE TITLE
Bootcamp presentation: presenter notes

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#266]
Based on slides and exercises write up presenter notes for the first round of training

**Comment by hpdang** [comment]
Ready to review https://docs.google.com/presentation/d/1pWUSnFxKJgjENcLwOFHa9Uzi0oD4gZs_1IMwq7ZbxBQ/edit#slide=id.g10dae75427_0_294

**Comment by perploug** [comment]
Quick question - is this the same slide deck as the one used in the presentation, and can we we simple rename this deck to be the actual deck used - so we avoid having 2 decks to maintain?

**Comment by perploug** [comment]
All looks good - however it seems there are no notes after slide 42 - on purpose or don't have a recording from that part of the presentation?

**Comment by perploug** [comment]
@hpdang I will delete the old presentation file so this is promoted to the only deck
