### ISSUE TITLE
Website tech setup

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#3]
Tech setup for building the team website mvp

- [x] Investigate jekyll, hugo, GH pages, Netlify
- [x] ~~Jekyll setup~~
- [x] Website pages - index.html, css, js files
- [x] Catwatch data
- [ ] Travis CI setup
- [x] ~~greenhouse jobs api~~

**Comment by baggerspion** [comment]
Watch the "Jekyll setup" task here: #9

**Comment by perploug** [comment]
Investigated the greenhouse api - seems like the job pages uses a jobs.zalando.de proxy which only support a basic search against location. 

Would suggest the pragmatic solution to this, is to manually add/remove jobs to the web site for now.

**Comment by princiya** [comment]
@perploug Great, let's do it manually. Thank you for investigating!
