### ISSUE TITLE
Create a sign-off document for lead

### ISSUE THREAD

**Issue by hpdang** [zalando/zalando.github.io#343]
During the development of maintainer training material, we realized that we need to have a sign-off document for the project lead to support his decision whether he/she should approve a proposal to release something open source.

**Comment by perploug** [comment]
Guidance for leads doc: https://docs.google.com/document/d/1FqnfcbkA6xDifE7m4te2yWSsNizddMB0kqsHS--unfo/edit?usp=sharing 

Please review and a PR will be setup

**Comment by hpdang** [comment]
perhaps to include a checklist to make things easier for leads, please see my comment on the file.
