### ISSUE TITLE
Open Source License Scanning

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#384]
Provide guidance to engineers who add dependencies to projects on which license the dependency is under. 

- Supported formats: npm, yarn, pip, sbt, pom, gradle, maven
- Given a manifest file, the tool will detect dependencies and look up the license for this dependency. 
- Block PRs who use illegal licenses
- Add a comment to PRs with new dependencies in.

**Comment by pombredanne** [comment]
FWIW, I maintain https://github.com/nexB/scancode-toolkit that may be able to help with a few of your requirements.

**Comment by bocytko** [comment]
It's done with SBOM scans nowadays.

**Comment by pombredanne** [comment]
@bocytko you wrote:
> It's done with SBOM scans nowadays.

Can you elaborate what you mean?

**Comment by bocytko** [comment]
We use data from Software Bill of Materials (SBOM) for license checks (and [other use cases](https://engineering.zalando.com/posts/2023/04/how-sboms-change-the-dependency-game.html)).
