### ISSUE TITLE
Add PR review checklist

### ISSUE THREAD

**Issue by pheanex** [zalando/zalando.github.io#393]
## Add PR review checklist

As we have a lot of things to check on PullRequests (Compliance, Security) it would help if we had a checklist as template in PRs that we can just tick of. That way we do our reviews more carefully and do not forget about things that easily.

### Expected delivery

A template that we can include in our Github repositories with all the items we have to check on each PR and checkboxes behind each item, so we can tick them off.

**Comment by sharath2106** [comment]
@pheanex I can take this up if no one is working on this. I would get back to you if I'm stuck.

**Comment by bocytko** [comment]
Such template is now part of Engineering Docs.
