### ISSUE TITLE
bug: blog/page1 gives 404 not found

### ISSUE THREAD

**Issue by lorenzocestaro** [zalando/zalando.github.io#405]
Hi guys,
great work with the open source management at Zalando!

I found a bug while browsing your website: when you click `1` on the blog pagination `nav` you get a `404` because route `blog/page1` does not exists, it is actually just `blog/`.
It should only be a matter of adding and extra condition inside `_includes/pagination.html` as you can see in [this](https://blog.webjeda.com/jekyll-pagination/) tutorial.

Keep it up

**Comment by szafranek** [comment]
Fixed in https://github.com/zalando/zalando.github.io/pull/423
