### ISSUE TITLE
404 on zappr link

### ISSUE THREAD

**Issue by mifriis** [zalando/zalando.github.io#407]
## Task Headline

Simple fix for an outdated link

### Tasks

Update it to: https://github.com/zalando/zappr

### Expected delivery

Any time

## Stakeholders

Any sane person :)

## How do we measure the task was completed

n/a

**Comment by mifriis** [comment]
Pull Request here:

https://github.com/zalando/zalando.github.io/pull/408

**Comment by bocytko** [comment]
@szafranek I believe this one can also be closed
