### ISSUE TITLE
Typos in PR and issue templates

### ISSUE THREAD

**Issue by szafranek** [zalando/zalando.github.io#426]
## Task Headline

There are a few typos and punctuation mistakes in the PR and issue template files.

### Expected delivery

Updated templates with fixed mistakes.

**Comment by ePaul** [comment]
Is this done in #427?

I'm somewhat questioning whether [this PR template](https://github.com/zalando/zalando.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md) really makes sense for a mostly documentation repository (both in its old and new form) – the "types of change" will mostly not be applicable.

(It is a fine example for other projects, but it likely shouldn't apply to this project.)

**Comment by szafranek** [comment]
> Is this done in #427?

Yes. Closing this ticket now.

> I'm somewhat questioning whether [this PR template](https://github.com/zalando/zalando.github.io/blob/master/.github/PULL_REQUEST_TEMPLATE.md) really makes sense for a mostly documentation repository (both in its old and new form) – the "types of change" will mostly not be applicable.

+1
