### ISSUE TITLE
Not Added Copyright Notice at bottom of a site

### ISSUE THREAD

**Issue by RishitaGangwal** [zalando/zalando.github.io#433]
A website — graphics, content, visual elements — is copyrighted at the time of development. So putting the copyright notice on the bottom of a site states that the material displayed is not to be used without permission of the owner. I would like to add copyright notice at the bottom of a site.

Please assign me this an issue.

Thanks!

**Comment by ePaul** [comment]
Hi, I don't think the copyright notice adds much value. The content is copyrighted anyways, whether or not there is a notice.
