### ISSUE TITLE
Update stats on website to include _all_ orgs and not just the Zalando org

### ISSUE THREAD

**Issue by baggerspion** [zalando/zalando.github.io#59]
Currently the stats on the first page only reflect the main Zalando org. These should be updated to include:

- [ ] zalando-incubator
- [ ] zalando-nakadi
- [ ] zalando-stups
- [ ] zalando-zmon
- [ ] zalandoresearch

**Comment by princiya** [comment]
[Catwatch](https://github.com/zalando-incubator/catwatch) currently supports only 3 organisations - https://github.com/zalando-incubator/catwatch/blob/master/catwatch-backend/src/main/resources/application.properties#L4.

We need to add the additional Zalando Github organisations into the above file. This means we will have to update Catwatch and is not in our current sprint scope. Hence, `On Hold` temporarily.

**Comment by perploug** [comment]
Website has been updated with the latest stats - we won't spend time on updating catwatch with more orgs as we will be decommissioning it anyways.
