### ISSUE TITLE
Place the current zalando.github.io content in ost/projects and restyle

### ISSUE THREAD

**Issue by baggerspion** [zalando/zalando.github.io#60]
We need to retain the content at zalando.github.io but make it the project subfolder of the new website. Should be restyled using dress code.

**Comment by princiya** [comment]
Observations / Notes:

- This is a private repo - https://github.com/zalando/zalando.github.io
- The content into `zalando.github.io` comes from this repository - https://github.com/zalando-incubator/zalando.github.io-dev
   - Users are encouraged to open Pull Requests into the above repository.
- The following lines from [this](https://github.com/zalando-incubator/zalando.github.io-dev/blob/master/gulpfile.js#L210) file take care of pushing the compiled web application into the [main](https://github.com/zalando/zalando.github.io) repository.

**Comment by princiya** [comment]
Next steps:

- [ ] ~~Tweak the `gulp` configuration file~~
   - Add a hook into [this](https://github.com/zalando-incubator/zalando.github.io-dev/blob/master/gulpfile.js#L210) file to be able to push the compiled web application into the `/projects` folder of this `OST` repository.

As discussed, here are the next steps:

- Create `/projects/index.html`
- Pull `catwatch` data
- Show all repositories
- Filter by technologies and organisations
