### ISSUE TITLE
Archive how-to-oss repository

### ISSUE THREAD

**Issue by princiya** [zalando/zalando.github.io#72]
## Task Headline

Archive this repository https://github.com/zalando/zalando-howto-open-source because we will refactor the content there and add it on opensource's website.

### Tasks

- [x] Archive the repository https://github.com/zalando/zalando-howto-open-source

## Stakeholders

Who do we need to colloborate with to make this happen? - add the deparment to get in touch with

- [x] Guild
- [ ] Tech (mailing list)

## How do we measure the task was completed
How do we measure impact 

  1.
  1.
  1.

**Comment by perploug** [comment]
Starting to remove links to this document and replace with the opensource.zalando docs page.

Updated:
- OS Guild Page

Pages which should include a link to these docs:
- https://rulesofplay.docs.zalando.net/OS/os/
- https://github.bus.zalan.do/opensource/reviewgroupdocs

**Comment by perploug** [comment]
Adding a deprecation notice to the github page which directs users to the opensource.zalando.com site documentation

**Comment by perploug** [comment]
Sent an email to the OS guild mailing list on the change

**Comment by baggerspion** [comment]
I think this is good to be archived now.
