### ISSUE TITLE
Review current projects in the main zalando org

### ISSUE THREAD

**Issue by perploug** [zalando/zalando.github.io#75]
## Description

Review the currently graduated projects to determine if there are projects that does not live
up to the standards set in #73 

### Tasks
This is the concreate tasks to complete before the task is marked as done

- [ ] Review org projects
- [ ] Notify maintainers of issues

### Expected delivery

- List of projects that does not live up to the standards set by #73 
- Maintainers contacted and informed of issues with a deadline of expected fix

**Comment by princiya** [comment]
Community metrics for orgs in zalando:

![screen shot 2018-06-08 at 11 29 25](https://user-images.githubusercontent.com/8022693/41150883-6a9eb33e-6b0f-11e8-8739-d950d8c063b8.png)
![screen shot 2018-06-08 at 11 30 10](https://user-images.githubusercontent.com/8022693/41150943-907ff87e-6b0f-11e8-9474-1d8703a1dec8.png)
![screen shot 2018-06-08 at 11 30 27](https://user-images.githubusercontent.com/8022693/41150885-6ad1843a-6b0f-11e8-9b64-046090f7b6b6.png)

**Comment by princiya** [comment]
| Name | Contributors | Health Percentage | COC | Contributing | Issue Template | PR Template | Readme | License | Stars | Forks
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
https://github.com/zalando/riptide| 11| 100| 1| 1| 0| 1| 1| MIT License| 66| 10
https://github.com/zalando/jackson-datatype-money| 10| 100| 1| 1| 0| 1| 1| MIT License| 82| 15
https://github.com/zalando/problem| 4| 100| 1| 1| 0| 1| 1| MIT License| 150| 26
https://github.com/zalando/problem-spring-web| 11| 100| 1| 1| 0| 1| 1| MIT License| 150| 27
https://github.com/zalando/logbook| 16| 100| 1| 1| 0| 1| 1| MIT License| 216| 40
https://github.com/zalando/dress-code| 14| 100| 1| 1| 1| 0| 1| MIT License| 109| 18
https://github.com/zalando/nakadi| 32| 100| 1| 1| 0| 1| 1| MIT License| 317| 86
https://github.com/zalando/tracer| 7| 100| 1| 1| 0| 1| 1| MIT License| 79| 21
https://github.com/zalando/faux-pas| 2| 100| 1| 1| 0| 1| 1| MIT License| 39| 1
https://github.com/zalando/zalenium| 29| 100| 1| 1| 1| 1| 1| Other| 945| 164
https://github.com/zalando/connexion| 77| 83| 0| 1| 1| 1| 1| Other| 1282| 245
https://github.com/zalando/grafter| 13| 83| 1| 1| 0| 0| 1| MIT License| 225| 23
https://github.com/zalando/zalando.github.io| 3| 83| 0| 1| 1| 1| 1| MIT License| 0| 4
https://github.com/zalando/pg_view| 13| 66| 0| 1| 0| 0| 1| Other| 352| 30
https://github.com/zalando/spring-cloud-config-aws-kms| 9| 66| 0| 1| 0| 0| 1| Apache License 2.0| 49| 19
https://github.com/zalando/package-build| 8| 66| 0| 1| 0| 0| 1| MIT License| 31| 4
https://github.com/zalando/friboo| 11| 66| 0| 1| 0| 0| 1| Apache License 2.0| 113| 14
https://github.com/zalando/spilo| 22| 66| 0| 1| 0| 0| 1| Apache License 2.0| 330| 38
https://github.com/zalando/patroni| 39| 66| 0| 1| 0| 0| 1| MIT License| 1698| 158
https://github.com/zalando/beard| 15| 66| 0| 1| 0| 0| 1| Other| 79| 20
https://github.com/zalando/skipper| 50| 66| 0| 1| 0| 0| 1| Other| 1107| 103
https://github.com/zalando/gin-oauth2| 8| 66| 0| 1| 0| 0| 1| MIT License| 113| 19
https://github.com/zalando/ghe-backup| 6| 66| 0| 1| 0| 0| 1| Apache License 2.0| 16| 3
https://github.com/zalando/zappr| 13| 66| 0| 1| 0| 0| 1| Other| 367| 35
https://github.com/zalando/elm-street-404| 7| 66| 0| 1| 0| 0| 1| MIT License| 159| 8
https://github.com/zalando/tailor| 32| 66| 0| 1| 0| 0| 1| Other| 614| 81
https://github.com/zalando/zalando-howto-open-source| 16| 66| 0| 0| 0| 1| 1| Creative Commons Attribution 4.0| 679| 76
https://github.com/zalando/restful-api-guidelines| 36| 66| 0| 1| 0| 0| 1| Creative Commons Attribution 4.0| 703| 142
https://github.com/zalando/expan| 8| 66| 0| 1| 0| 0| 1| MIT License| 160| 29
https://github.com/zalando/go-keyring| 4| 66| 0| 1| 0| 0| 1| MIT License| 95| 11
https://github.com/zalando/SwiftMonkey| 7| 66| 1| 0| 0| 0| 1| MIT License| 1204| 97
https://github.com/zalando/zally| 28| 66| 0| 1| 0| 0| 1| MIT License| 149| 26
https://github.com/zalando/PGObserver| 18| 50| 0| 0| 0| 0| 1| Other| 251| 54
https://github.com/zalando/gulp-check-unused-css| 5| 50| 0| 0| 0| 0| 1| Other| 359| 17
https://github.com/zalando/python-nsenter| 5| 50| 0| 1| 0| 0| 1| Other| 65| 10
https://github.com/zalando/zmon| 8| 50| 0| 0| 0| 0| 1| Other| 209| 33
https://github.com/zalando/tokens| 18| 50| 0| 0| 0| 0| 1| Apache License 2.0| 86| 42
https://github.com/zalando/innkeeper| 9| 50| 0| 0| 0| 0| 1| Other| 113| 15
https://github.com/zalando/tech-radar| 7| 50| 0| 0| 0| 0| 1| MIT License| 228| 72
https://github.com/zalando/intellij-swagger| 10| 50| 0| 0| 0| 0| 1| MIT License| 551| 34
https://github.com/zalando/https://github.com/zalando/failsafe-actuator| 9| 50| 0| 0| 0| 0| 1| MIT License| 28| 8
https://github.com/zalando/engineering-principles| 8| 50| 0| 0| 0| 0| 1| Creative Commons Attribution 4.0| 24| 2
https://github.com/zalando/shop-api-documentation| 1| 33| 0| 0| 0| 0| 1| | 0| 0

**Comment by princiya** [comment]
Corresponding metabase query to get the above results:

```
select Repository.name, count(Contribution.user_id) as Contributors, CommunityProfile.health_percentage, CommunityProfile.code_of_conduct, CommunityProfile.contributing, CommunityProfile.issue_template, CommunityProfile.pull_request_template, CommunityProfile.readme, CommunityProfile.license, Repository.stars, Repository.forks
from CommunityProfile, Repository, Organisation, Contribution
where CommunityProfile.repository_id=Repository.id and Repository.organisation_id=Organisation.id and Organisation.name='zalando' and Contribution.repository_id=Repository.id
group by Contribution.repository_id
order by health_percentage desc
```
